markaz/markaz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('principle/', include('principle.urls')),
    path('teacher/', include('teacher.urls')),
    path('student/', include('student.urls')),
]

if settings.DEBUG:
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

markaz/principle/urls.py
from django.urls import path
from principle import views
from django.contrib.auth.views import LogoutView

urlpatterns = [
    # path('', views.checkpath),
    path('no_permission/', views.no_permission, name='no_permission'),

    # Register teacher and student

    path('register/teacher/', views.register_teacher, name='teacher-registration'),
    path('register/student/', views.register_student, name='student-registration'),

    # Add country, state, city

    path('add-country/', views.CountryCreateView.as_view(), name='add-country'),

    path('add-state/', views.StateCreateView.as_view(), name='add-state'),

    path('add-city/', views.CityCreateView.as_view(), name='add-city'),

    # Load state and city

    path('load_states/', views.LoadStatesView.as_view(), name='load_states'),
    path('load_cities/', views.LoadCitiesView.as_view(), name='load_cities'),

    # Country List, Update

    path('country_list/', views.CountryList.as_view(), name='country_list'),
    path('update_country/<int:country_id>/', views.UpdateCountry.as_view(), name='update_country'),
    path('delete_country/<int:country_id>/', views.DeleteCountry.as_view(), name='delete_country'),

    # State List, Update

    path('state_list/', views.StateList.as_view(), name='state_list'),
    path('update_state/<int:state_id>/', views.UpdateState.as_view(), name='update_state'),
    path('delete_state/<int:state_id>/', views.DeleteState.as_view(), name='delete_state'),

    # City List, Update

    path('city_list/', views.CityList.as_view(), name='city_list'),
    path('update_city/<int:city_id>/', views.UpdateCity.as_view(), name='update_city'),
    path('delete_city/<int:city_id>/', views.DeleteCity.as_view(), name='delete_city'),

    # For Logout

    path('logout/', LogoutView.as_view(), name='logout'),
    
    # For Admin Home

    path('admin-home', views.AdminHome.as_view(), name='admin-home'),

    # List Student and Teacher

    path('list_student/', views.StudentListView.as_view(), name='list_student'),
    path('list_teacher/', views.TeacherListView.as_view(), name='list_teacher'),

    # Update and Delete Student

    path('update_student/<int:student_id>/', views.UpdateStudent.as_view(), name='update_student'),
    path('student/delete/<int:student_id>/', views.DeleteStudent.as_view(), name='delete_student'),

    # Update and Delete Teacher

    path('update_teacher/<int:teacher_id>/', views.UpdateTeacher.as_view(), name='update_teacher'),
    path('teacher/delete/<int:teacher_id>/', views.DeleteTeacher.as_view(), name='delete_teacher'),

    # List of Deleted Student and Teacher

    path('deleted_teacher_list/', views.DeletedTeacherList.as_view(), name='deleted_teacher_list'),
    path('deleted_student_list/', views.DeletedStudentList.as_view(), name='deleted_student_list'),


    # Export and Import teacher and student

    path('export-students/', views.ExportStudentsView.as_view(), name='export_students'),
    # path('import-students/', views.import_students, name='import_students'),
    path('export-teachers/', views.ExportTeachersView.as_view(), name='export_teachers'),


    # Student crud operation

    path('studentlist/', views.studentlist, name='studentlist'),
    path('createstudent/', views.createstudent, name='createstudent'),
    path('studentupdate/<int:id>', views.studentupdate, name='studentupdate'),
    path('deletestudent/<int:id>', views.deletestudent, name='deletestudent'),


    # Teacher crud operation

    path('teacherlist/', views.teacherlist, name='teacherlist'),
    path('createteacher/', views.createteacher, name='createteacher'),
    path('teacherupdate/<int:id>', views.teacherupdate, name='teacherupdate'),
    path('deleteteacher/<int:id>', views.deleteteacher, name='deleteteacher'),

    # path('otp_verification/', views.otp_verification_view, name='otp_verification'),

    # Student Grade Card

    path('create_course/', views.CreateCourseView.as_view(), name='create_course'),
    path('add-exam/', views.CreateExamView.as_view(), name='add-exam'),
    path('add-subject/', views.CreateSubjectView.as_view(), name='add-subject'),
    path('add-academic-detail/', views.AddAcademicDetail.as_view(), name='add-academic-detail'),
    path('students/', views.StudentList.as_view(), name='student-list'),
    path('students/<int:student_id>/', views.AcademicDetailView.as_view(), name='view-academic-details'),
    path('export-academic-detail/', views.ExportAcademicDetail.as_view(), name='export_academic_detail'),

    # Course list, update, delete

    path('course_list/', views.CourseList.as_view(), name='course_list'),
    path('update_course/<int:course_id>/', views.UpdateCourse.as_view(), name='update_course'),
    path('delete_course/<int:course_id>/', views.DeleteCourse.as_view(), name='delete_course'),
    # Exam list, update, delete

    path('exam_list/', views.ExamList.as_view(), name='exam_list'),
    path('update_exam/<int:exam_id>/', views.UpdateExam.as_view(), name='update_exam'),
    path('delete_exam/<int:exam_id>/', views.DeleteExam.as_view(), name='delete_exam'),

    # Subject list, update, delete

    path('subject_list/', views.SubjectList.as_view(), name='subject_list'),
    path('update_subject/<int:subject_id>/', views.UpdateSubject.as_view(), name='update_subject'),
    path('delete_subject/<int:subject_id>/', views.DeleteSubject.as_view(), name='delete_subject'),

    # Teacher Attendance View

    path('view-teacher-attendance/', views.ViewTeacherAttendance.as_view(), name='view_teacher_attendance'),
    path('export-teacher-attendance/', views.ExportTeacherAttendance.as_view(), name='export_teacher_attendance'),

    # Student Course Completion

    path('create/', views.CreateCertificate.as_view(), name='create_certificate'),
    path('generate/<int:pk>/', views.GenerateCertificate.as_view(), name='generate_certificate'),
    path('certificate/', views.CertificateList.as_view(), name='certificate_list'),

    # Creating Announcements

    path('create_announcement/', views.CreateAnnouncement.as_view(), name='create_announcement'),
    path('announcement_list/', views.AnnouncementsList.as_view(), name='announcement_list'),

    # Update and Delete Announcement

    path('update_announcement/<int:announcement_id>/', views.UpdateAnnouncement.as_view(), name='update_announcement'),
    path('delete_announcement/<int:announcement_id>/', views.DeleteAnnouncement.as_view(), name='delete_announcement'),


    # Chat Module

    path('add_room/', views.CreateRoom.as_view(), name='add_room'),
    path('rooms/', views.AdminRoom.as_view(), name='admin_rooms'),
    path('room/<int:room_id>/', views.RoomView.as_view(), name='admin_room'),
    
]

markaz/user/urls.py
from django.urls import path
from user import views


urlpatterns = [
    path('', views.checkpath),
    path('login/', views.custom_login, name='custom_login'),
    path('otp_verification/', views.otp_verification_view, name='otp_verification'),

]

markaz/principle/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone
from user.models import CustomUser
# Create your models here.
class Country(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    
class State(models.Model):
    name = models.CharField(max_length=100)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
class City(models.Model):
    name = models.CharField(max_length=100)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    state = models.ForeignKey(State, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
class Teacher(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    reg_id = models.CharField(max_length=50,default="TR", unique=True)
    name = models.CharField(max_length=50)
    contact = models.CharField(max_length=50)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    state = models.ForeignKey(State, on_delete=models.CASCADE)
    city = models.ForeignKey(City, on_delete=models.CASCADE)


    def __str__(self):
        return self.name
    

class Courses(models.Model):
    id = models.AutoField(primary_key=True)
    course_name = models.CharField(max_length=250)
    description = models.CharField(max_length=250)
    course_fee = models.CharField(max_length=100)

    def __str__(self):
        return self.course_name
    

class Student(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    reg_id = models.CharField(max_length=50, default="STD", unique=True)
    name = models.CharField(max_length=50)
    contact = models.CharField(max_length=50)
    course = models.ForeignKey(Courses, on_delete= models.DO_NOTHING)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    state = models.ForeignKey(State, on_delete=models.CASCADE)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    start_year = models.DateField()
    end_year = models.DateField()

    
    def __str__(self):
        return self.name


class Exam(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    
class Subject(models.Model):
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
    course = models.ForeignKey(Courses, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)


    def __str__(self):
        return self.name
    
class AcademicDetail(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
    course = models.ForeignKey(Courses, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    individual_score = models.DecimalField(max_digits=5, decimal_places=2)
    grade = models.CharField(max_length=2)
    total_score = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    overall_grade = models.CharField(max_length=2, blank=True, null=True)

    def __str__(self):
        return f"{self.student.name}'s {self.subject} Score"
        
class Certificate(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    course = models.ForeignKey(Courses, on_delete=models.CASCADE)


    def __str__(self):
        return f"Certificate for {self.student.name} - {self.course.course_name}"

CustomUser = get_user_model()

class Announcement(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    show_to_teachers = models.BooleanField(default=False, verbose_name="Show to Teachers")
    show_to_students = models.BooleanField(default=False, verbose_name="Show to Students")
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)


    def __str__(self):
        return self.title
    
class Room(models.Model):
    name = models.CharField(max_length=250)
    course = models.ForeignKey(Courses, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name
    
class Message(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    content = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('date_added',)

    def __str__(self):
        return self.user


    

markaz/principle/forms.py
from django import forms
from principle.models import *


class StudentRegisterForm(forms.ModelForm):
    class Meta:
        model = Student
        exclude = ['user']

class TeacherRegisterForm(forms.ModelForm):

    class Meta:
        model = Teacher
        exclude = ['user']

class CoursesForm(forms.ModelForm):
    class Meta:
        model = Courses
        fields = '__all__'

class ExamForm(forms.ModelForm):
    class Meta:
        model = Exam
        fields = '__all__'

class SubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = '__all__'

class AcademicDetailForm(forms.ModelForm):
    class Meta:
        model = AcademicDetail
        fields = ['student', 'exam', 'course', 'subject', 'individual_score']

class CertificateForm(forms.ModelForm):
    class Meta:
        model = Certificate
        fields = ['student', 'course']


class AnnouncementForm(forms.ModelForm):
    class Meta:
        model = Announcement
        fields = ['title', 'content', 'show_to_teachers', 'show_to_students']

class CountryForm(forms.ModelForm):
    class Meta:
        model = Country
        fields = '__all__'

class StateForm(forms.ModelForm):
    class Meta:
        model = State
        fields = '__all__'


class CityForm(forms.ModelForm):
    class Meta:
        model = City
        fields = '__all__'

class RoomForm(forms.ModelForm):
    class Meta:
        model = Room
        fields = '__all__'

markaz/templates/principle/add_academic_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Academic Details</title>
    <style>
        /* CSS styles */
        body {
          font-family: Arial, sans-serif;
          background-color: #f2f2f2;
        }
  
        form {
          background-color: #fff;
          padding: 20px;
          border-radius: 5px;
          width: 300px;
          margin: 0 auto;
          margin-top: 50px;
          box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        }
  
        h1 {
          text-align: center;
          color: #333;
        }
  
        label {
          display: block;
          margin-bottom: 10px;
          color: #666;
        }
  
        input[type="text"]{
          width: 100%;
          padding: 10px;
          border-radius: 5px;
          border: none;
          margin-bottom: 20px;
          box-sizing: border-box;
          border: 1px solid #ccc;
        }
  
        button[type="submit"] {
          background-color: #333;
          color: #fff;
          padding: 10px 20px;
          border: none;
          border-radius: 5px;
          cursor: pointer;
          display: block;
          margin: 0 auto;
        }
        
        button[type="submit"]:hover {
          background-color: #555;
        }
        p{
            text-align : center;

        }
    </style>
</head>
<body>
    <h1>Add Academic Details</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <br><br>
   <p> <a href="{% url 'admin-home' %}">Back to Home</a></p>

</body>
</html>

markaz/templates/principle/add_country.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Country</title>
    <style>
        /* CSS styles */
        body {
          font-family: Arial, sans-serif;
          background-color: #f2f2f2;
        }
  
        form {
          background-color: #fff;
          padding: 20px;
          border-radius: 5px;
          width: 300px;
          margin: 0 auto;
          margin-top: 50px;
          box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        }
  
        h1 {
          text-align: center;
          color: #333;
        }
  
        label {
          display: block;
          margin-bottom: 10px;
          color: #666;
        }
  
        input[type="text"]{
          width: 100%;
          padding: 10px;
          border-radius: 5px;
          border: none;
          margin-bottom: 20px;
          box-sizing: border-box;
          border: 1px solid #ccc;
        }
  
        button[type="submit"] {
          background-color: #333;
          color: #fff;
          padding: 10px 20px;
          border: none;
          border-radius: 5px;
          cursor: pointer;
          display: block;
          margin: 0 auto;
        }
        
        button[type="submit"]:hover {
          background-color: #555;
        }
        p{
            text-align : center;

        }
    </style>
</head>
<body>
    <h1>Add Country</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <p> <a href="{% url "admin-home" %}">Back to home</a> </p>

</body>
</html>

markaz/templates/principle/add_state.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add State</title>
    <style>
        /* CSS styles */
        body {
          font-family: Arial, sans-serif;
          background-color: #f2f2f2;
        }
  
        form {
          background-color: #fff;
          padding: 20px;
          border-radius: 5px;
          width: 300px;
          margin: 0 auto;
          margin-top: 50px;
          box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        }
  
        h1 {
          text-align: center;
          color: #333;
        }
  
        label {
          display: block;
          margin-bottom: 10px;
          color: #666;
        }
  
        input[type="text"]{
          width: 100%;
          padding: 10px;
          border-radius: 5px;
          border: none;
          margin-bottom: 20px;
          box-sizing: border-box;
          border: 1px solid #ccc;
        }
  
        button[type="submit"] {
          background-color: #333;
          color: #fff;
          padding: 10px 20px;
          border: none;
          border-radius: 5px;
          cursor: pointer;
          display: block;
          margin: 0 auto;
        }
        
        button[type="submit"]:hover {
          background-color: #555;
        }
        p{
            text-align : center;

        }
    </style>
</head>
<body>
    <h1>Add State</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <p> <a href="{% url "admin-home" %}">Back to home</a> </p>

</body>
</html>

markaz/templates/principle/add_subject.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Subject</title>
    <style>
        /* CSS styles */
        body {
          font-family: Arial, sans-serif;
          background-color: #f2f2f2;
        }
  
        form {
          background-color: #fff;
          padding: 20px;
          border-radius: 5px;
          width: 300px;
          margin: 0 auto;
          margin-top: 50px;
          box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        }
  
        h2 {
          text-align: center;
          color: #333;
        }
  
        label {
          display: block;
          margin-bottom: 10px;
          color: #666;
        }
  
        input[type="text"],
        input[type="password"],
        input[type="email"] {
          width: 100%;
          padding: 10px;
          border-radius: 5px;
          border: none;
          margin-bottom: 20px;
          box-sizing: border-box;
          border: 1px solid #ccc;
        }
  
        button[type="submit"] {
          background-color: #333;
          color: #fff;
          padding: 10px 20px;
          border: none;
          border-radius: 5px;
          cursor: pointer;
          display: block;
          margin: 0 auto;

        }
  
        button[type="submit"]:hover {
          background-color: #555;
        }
        p{
            text-align : center;

        }
      </style>
</head>
<body>
    <h2>Add Subject</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <p> <a href="{% url "admin-home" %}">Back to home</a> </p>

</body>
</html>

markaz/templates/principle/announcements_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="refresh" content="10">
    <title>Announcements</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f5f5f5;
            margin: 0;
            padding: 0;
        }

        h1 {
            background-color: #007BFF;
            color: #fff;
            text-align: center;
            padding: 20px 0;
        }

        ul {
            list-style: none;
            padding: 0;
        }

        li {
            background-color: #fff;
            margin: 20px auto;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
            transition: transform 0.2s;
            position: relative;
        }

        li:hover {
            transform: translateY(-5px);
        }

        strong {
            color: #007BFF;
        }

        a {
            text-decoration: none;
            color: #007BFF;
            font-weight: bold;
        }

        a:hover {
            text-decoration: underline;
        }

        p {
            text-align: center;
        }

        .announcement-content {
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .btn-container {
            display: flex;
        }

        .btn-container a {
            text-decoration: none;
            color: #007BFF;
            font-weight: bold;
            margin-right: 10px;
        }
    </style>
</head>
<body>
    <h1>Announcements</h1>
    <ul>
        {% for announcement in announcements %}
            <li>
                <div class="announcement-content">
                    <div>
                        <strong>{{ announcement.title }}</strong><br>
                        {{ announcement.content }}<br>
                        Posted by: {{ announcement.user }}<br>
                        Date: {{ announcement.created_at }}
                    </div>
                    <div class="btn-container">
                        <a href="{% url 'update_announcement' announcement.id %}">Update</a>
                        <a href="{% url 'delete_announcement' announcement.id %}">Delete</a>
                    </div>
                </div>
            </li>
        {% endfor %}
    </ul>
    <p><a href="{% url 'admin-home' %}">Back to home</a></p>
</body>
</html>

markaz/templates/principle/delete_country.html
<!DOCTYPE html>
<html>
<head>
    <title>Delete Country</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f5f5f5;
            margin: 0;
            padding: 0;
            text-align: center;
        }

        h2 {
            background-color: #007BFF;
            color: #fff;
            padding: 10px;
        }

        p {
            font-size: 18px;
            margin: 20px 0;
        }

        form {
            margin: 20px 0;
        }
        button {
            background-color: #f44336;
            color: white;
            padding: 10px 20px;
            border: none;
            cursor: pointer;
        }
        button:hover {
            background-color: #d32f2f;
        }

        a {
            text-decoration: none;
            color: #007BFF;
        }

        a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <h2>Delete Country</h2>
    <p>Are you sure you want to delete the country?</p>
    <p><strong>{{ country.name }}</strong></p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Delete</button>
        <br><br>
        <a href="{% url 'country_list' %}">Cancel</a>
    </form>
</body>
</html>

markaz/templates/principle/delete_state.html
<!DOCTYPE html>
<html>
<head>
    <title>Delete State</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f5f5f5;
            margin: 0;
            padding: 0;
            text-align: center;
        }

        h2 {
            background-color: #007BFF;
            color: #fff;
            padding: 10px;
        }

        p {
            font-size: 18px;
            margin: 20px 0;
        }

        form {
            margin: 20px 0;
        }
        button {
            background-color: #f44336;
            color: white;
            padding: 10px 20px;
            border: none;
            cursor: pointer;
        }
        button:hover {
            background-color: #d32f2f;
        }

        a {
            text-decoration: none;
            color: #007BFF;
        }

        a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <h2>Delete State</h2>
    <p>Are you sure you want to delete the state?</p>
    <p><strong>{{ state.name }}</strong></p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Delete</button>
        <br><br>
        <a href="{% url 'state_list' %}">Cancel</a>
    </form>
</body>
</html>

markaz/templates/principle/register_student.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student Registration</title>
      <style>
        /* CSS styles */
        body {
          font-family: Arial, sans-serif;
          background-color: #f2f2f2;
        }
  
        form {
          background-color: #fff;
          padding: 20px;
          border-radius: 5px;
          width: 300px;
          margin: 0 auto;
          margin-top: 50px;
          box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        }
  
        h2 {
          text-align: center;
          color: #333;
        }
  
        label {
          display: block;
          margin-bottom: 10px;
          color: #666;
        }
  
        input[type="text"],
        input[type="password"],
        input[type="email"] {
          width: 100%;
          padding: 10px;
          border-radius: 5px;
          border: none;
          margin-bottom: 20px;
          box-sizing: border-box;
          border: 1px solid #ccc;
        }
  
        button[type="submit"] {
          background-color: #333;
          color: #fff;
          padding: 10px 20px;
          border: none;
          border-radius: 5px;
          cursor: pointer;
          display: block;
          margin: 0 auto;
        }
  
        button[type="submit"]:hover {
          background-color: #555;
        }
        p{
            text-align : center;

        }
      </style>
      <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
      <script src="https://www.google.com/recaptcha/api.js" async defer></script>
      <script src="https://www.google.com/recaptcha/api.js?render=6Ldy03QoAAAAACgH_pge04Y5eEqZRwg8hy6AxUF3"></script>
  
</head>
<body>
    <h2>Student Registration</h2>
    <form method="post">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Username" required>
        <input type="password" name="password" placeholder="Password" required>
        <input type="email" name="email" placeholder="E-mail" required>
        <input type="text" name="reg_id" value="STD" placeholder="Reg_Id" required>
        <input type="text" name="name" placeholder="Name" required>
        <input type="text" name="contact" placeholder="Contact" required>
        <label for="Course">Course:</label>
        {{form.course}}
        <br><br>
        <label for="country">Country:</label>
        {{ form.country }}
        <br><br>
        <label for="state">State:</label>
        {{ form.state }}
        <br><br>
        <label for="city">City:</label>
        {{ form.city }}
        <br><br>
        <label for="start_year">Start_year</label>
        <input type="date" name="start_year" required>
        <br><br>
        <label for="end_year">End_year</label>
        <input type="date" name="end_year" required>
        <br><br>
        <input type="text" id="token" name="token" hidden>

        <button type="submit">Add Student</button>
    </form>

    <p> <a href="{% url "admin-home" %}">Back to home</a></p>


    <script>
      var loadStatesURL = "{% url 'load_states' %}";
      var loadCitiesURL = "{% url 'load_cities' %}";

      $(document).ready(function () {
          $("#id_country").change(function () {
              var country_id = $(this).val();
              $.ajax({
                  url: loadStatesURL,
                  data: {
                      'country_id': country_id
                  },
                  success: function (data) {
                      var state_dropdown = $("#id_state");
                      state_dropdown.empty();
                      state_dropdown.append($('<option value="">Select State</option>'));
                      $.each(data.states, function (i, state) {
                          state_dropdown.append($('<option>').text(state.name).attr('value', state.id));
                      });
                  }
              });
          });

          $("#id_state").change(function () {
              var state_id = $(this).val();
              $.ajax({
                  url: loadCitiesURL,
                  data: {
                      'state_id': state_id
                  },
                  success: function (data) {
                      var city_dropdown = $("#id_city");
                      city_dropdown.empty();
                      city_dropdown.append($('<option value="">Select City</option>'));
                      $.each(data.cities, function (i, city) {
                          city_dropdown.append($('<option>').text(city.name).attr('value', city.id));
                      });
                  }
              });
          });
      });
  </script>


  <script>
    grecaptcha.ready(function () {
        grecaptcha.execute('6Ldy03QoAAAAACgH_pge04Y5eEqZRwg8hy6AxUF3', { action: 'submit' }).then(function (token) {
            document.getElementById('token').value = token;
            console.log(token)
        });
    });
  </script>

  
</body>
</html>