markaz/markaz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('principle/', include('principle.urls')),
    path('teacher/', include('teacher.urls')),
    path('student/', include('student.urls')),
]

if settings.DEBUG:
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

markaz/teacher/urls.py
from django.urls import path
from teacher import views
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path('teacher_home/', views.TeacherHomeView.as_view(), name='teacher_home'),
    
    path('logout/', LogoutView.as_view(), name='logout'),

    # Add Study Material

    path('add_study_material/', views.AddStudyMaterialView.as_view(), name='add_study_material'),

    # Study Material List, View, Update, Delete

    path('uploded_materials/', views.UploadedStudyMaterialList.as_view(), name='uploded_materials'),

    path('view_materials/<int:material_id>/', views.ViewMaterials.as_view(), name='view_materials_teacher'),

    path('update_materials/<int:material_id>/', views.UpdateStudyMaterial.as_view(), name='update_studymaterial'),

    path('delete_study_material/<int:material_id>/', views.DeleteStudyMaterial.as_view(), name='delete_study_material'),

    # Mark Attendance
    
    path('mark_attendance/', views.MarkAttendance.as_view(), name='mark_attendance'),

    # View Announcement

    path('teacher_announcements/', views.TeacherAnnouncements.as_view(), name='teacher_announcements'),

    # Send Notification

    path('send_notification/', views.SendNotification.as_view(), name='send_notification'),

    # Notification List, Update, Delete

    path('notification_list/', views.ListNotifications.as_view(), name='list_notification'),
    path('update-notification/<int:notification_id>/', views.UpdateNotification.as_view(), name='update_notification'),
    path('delete_notification/<int:notification_id>/', views.DeleteNotification.as_view(), name='delete_notification'),


    # Teacher Profile

    path('teacher/profile/', views.TeacherProfileView.as_view() ,name='teacher_profile'),

    # Chat Room

    path('rooms/', views.RoomList.as_view(), name='teacher_rooms'),

    path('room/<int:room_id>/', views.RoomView.as_view(), name='teacher_room'),

    ]

markaz/user/urls.py
from django.urls import path
from user import views


urlpatterns = [
    path('', views.checkpath),
    path('login/', views.custom_login, name='custom_login'),
    path('otp_verification/', views.otp_verification_view, name='otp_verification'),

]

markaz/teacher/models.py
from django.db import models
from principle.models import *
from django.utils import timezone
# Create your models here.

class StudyMaterial(models.Model):
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    file = models.FileField(upload_to='study_materials/')
    uploaded_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.title
        

class TeacherAttendance(models.Model):
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    date = models.DateField()
    morning_attendance = models.BooleanField(default=False)
    afternoon_attendance = models.BooleanField(default=False)

    class Meta:
        unique_together = ('teacher', 'date')


    def __str__(self):
        return f"{self.teacher.name}'s Attendance on {self.date}"

    

class Notification(models.Model):
    sender = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    recipient = models.ForeignKey(Student, on_delete=models.CASCADE)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    seen = models.BooleanField(default=False)
    scheduled_at = models.DateTimeField()



    def __str__(self):
        return f"Notification from {self.sender.name} to {self.recipient.name}"

markaz/teacher/forms.py
from django import forms
from teacher.models import *


class StudyMaterialForm(forms.ModelForm):
    class Meta:
        model = StudyMaterial
        fields = ['title', 'description', 'file']


class NotificationForm(forms.ModelForm):
    scheduled_at = forms.DateTimeField(widget=forms.TextInput(attrs={'class' : 'datepicker'}))

    class Meta:
        model = Notification
        fields = ['recipient', 'message', 'scheduled_at']

markaz/teacher/views.py
from django.shortcuts import render, redirect
from principle.views import *
from django.contrib.auth.decorators import login_required
from teacher.models import *
from teacher.forms import *
from django.db.models import Sum
from django.contrib.auth import authenticate, login, logout
from django.utils.timezone import now
from django.views import View
from datetime import datetime, time
import pytz
from datetime import timedelta
from django.utils import timezone
from django.http import JsonResponse, HttpResponseForbidden, FileResponse
from django.views.generic import FormView, ListView
from django.views import View
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from teacher.mixins import teacher_required, TeacherRequiredMixin

# Create your views here.

def no_permission(request):
    return render(request, 'teacher/no_permission.html')

# Teacher Home

class TeacherHomeView(TeacherRequiredMixin,View):
    def get(self, request):
        return render(request, 'teacher/teacherhome.html')
# Add Study Materials

class AddStudyMaterialView(TeacherRequiredMixin,FormView):
    template_name = 'teacher/add_study_material.html'

    def get(self, request):
        form = StudyMaterialForm()
        context = {
            'form': form,
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = StudyMaterialForm(request.POST, request.FILES)
        if form.is_valid():
            study_material = form.save(commit=False)
            study_material.teacher = request.user.teacher
            study_material.save()
            return redirect('teacher_home')

        context = {
            'form': form,
        }
        return render(request, self.template_name, context)

# Study Material List, Update, Delete


class UploadedStudyMaterialList(View):
    def get(self, request):
        study_materials = StudyMaterial.objects.filter(teacher=request.user.teacher)
    
        context = {
            'study_materials': study_materials,
        }
    
        return render(request, 'teacher/uploded_materials.html', context)

class ViewMaterials(TeacherRequiredMixin,View):

    def get(self, request, material_id):
        material = get_object_or_404(StudyMaterial, pk=material_id)
        response = FileResponse(material.file)
        return response

class UpdateStudyMaterial(TeacherRequiredMixin, View):
    template_name = 'teacher/update_study_material.html'


    def get(self, request, material_id):
        material = StudyMaterial.objects.get(pk=material_id)
        form = StudyMaterialForm(instance=material)
        context = {
            'form': form,
            'material': material,
        }
        return render(request, self.template_name, context)

    def post(self, request, material_id):
        material = StudyMaterial.objects.get(pk=material_id)
        form = StudyMaterialForm(request.POST, request.FILES, instance=material)

        if form.is_valid():
            form.instance.teacher = request.user.teacher
            form.save()
            return redirect('uploded_materials')
        else:
            context = {
                'form': form,
                'material': material,
            }
            return render(request, self.template_name, context)

class DeleteStudyMaterial(TeacherRequiredMixin,View):
    template_name = 'teacher/delete_study_material.html'

    def get(self, request, material_id):
        material = get_object_or_404(StudyMaterial, pk=material_id)
        context = {'material': material}
        return render(request, self.template_name, context)

    def post(self, request, material_id):
        material = get_object_or_404(StudyMaterial, pk=material_id)
        material.delete()
        return redirect('teacher_home')

# Submit Attendance

class MarkAttendance(TeacherRequiredMixin,View):

    def get(self, request):

        teacher = request.user.teacher
        today = datetime.now().date()
        morning_start_time = time(7, 0) 
        afternoon_start_time = time(12, 0) 

        current_time = datetime.now().time()

        time_allowed_for_morning = current_time >= morning_start_time and current_time < afternoon_start_time

        time_allowed_for_afternoon = current_time >= afternoon_start_time

        try:
            attendance = TeacherAttendance.objects.get(teacher=teacher, date=today)

        except TeacherAttendance.DoesNotExist:

            attendance = TeacherAttendance(teacher=teacher, date=today)
            attendance.save()

        return render(request, 'teacher/mark_attendance.html', {
            'attendance': attendance,
            'time_allowed_for_morning': time_allowed_for_morning,
            'time_allowed_for_afternoon': time_allowed_for_afternoon,
        })


    def post(self, request):

        current_time = datetime.now().time()
        morning_start_time = time(7, 0)

        afternoon_start_time = time(12, 0)

        teacher = request.user.teacher
        today = datetime.now().date()

        if current_time > morning_start_time and current_time < afternoon_start_time:
            attendance_type = 'morning_attendance'

        elif current_time >= afternoon_start_time:
            attendance_type = 'afternoon_attendance'
        else:
            return render(request, 'teacher/error.html', {'message' : 'Attendance submission not allowed at this time'})


        try:
            attendance = TeacherAttendance.objects.get(teacher=teacher, date=today)
            setattr(attendance, attendance_type, request.POST.get(attendance_type) == 'on')
            attendance.save()
        except TeacherAttendance.DoesNotExist:

            attendance_data = {
                'teacher' : teacher,
                'date' : today,
                attendance_type : request.POST.get(attendance_type) == 'on'

            }
            attendance = TeacherAttendance(**attendance_data)
            attendance.save()

        return redirect('teacher_home')

# View Announcements

class TeacherAnnouncements(TeacherRequiredMixin,ListView):
    model = Announcement
    template_name = 'teacher/teacher_announcements.html'
    context_object_name = 'announcements'

    def get_queryset(self):
        one_day = timezone.now() - timedelta(days=1)
        return Announcement.objects.filter(created_at__gte=one_day, show_to_teachers=True)

# Send Notification

class SendNotification(TeacherRequiredMixin,View):
    template_name = 'teacher/send_notification.html'

    def get(self, request):
        form = NotificationForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = NotificationForm(request.POST)
        if form.is_valid():
            form.instance.sender = request.user.teacher
            form.save()
            return redirect('teacher_home')
        return render(request, self.template_name, {'form': form})

# List, Update, Delete Notification

class ListNotifications(TeacherRequiredMixin,View):
    template_name = 'teacher/list_notifications.html'

    def get(self, request):
        notifications = Notification.objects.filter(sender=request.user.teacher)
        return render(request, self.template_name, {'notifications': notifications})

class UpdateNotification(TeacherRequiredMixin,View):
    template_name = 'teacher/update_notification.html'

    def get(self, request, notification_id):
        notification = Notification.objects.get(pk=notification_id)
        form = NotificationForm(instance=notification)
        return render(request, self.template_name, {'form': form})

    def post(self, request, notification_id):
        notification = Notification.objects.get(pk=notification_id)
        form = NotificationForm(request.POST, instance=notification)
        if form.is_valid():
            form.instance.sender = request.user.teacher
            form.save()
            return redirect('list_notification')
        return render(request, self.template_name, {'form': form})

class DeleteNotification(TeacherRequiredMixin,View):
    template_name = 'teacher/delete_notification.html'

    def get(self, request, notification_id):
        notification = Notification.objects.get(pk=notification_id)
        context = {'notification': notification}
        return render(request, self.template_name, context)

    def post(self, request, notification_id):
        notification = Notification.objects.get(pk=notification_id)
        notification.delete()
        return redirect('list_notification')

# Teacher Profile

class TeacherProfileView(TeacherRequiredMixin,DetailView):
    def get(self, request):
        teacher = request.user.teacher
        return render(request, 'teacher/teacher_profile.html', {'teacher': teacher})

# Room List

class RoomList(TeacherRequiredMixin,ListView):

    def get(self, request):
        rooms = Room.objects.all()
        context = {
            'rooms' : rooms,
        }
        return render(request, 'teacher/rooms.html', context)

class RoomView(TeacherRequiredMixin,View):
    template_name = 'teacher/room.html'

    def get(self, request, room_id):
        room = get_object_or_404(Room, id=room_id)
        messages = Message.objects.filter(room=room)

        context = {
            'room': room,
            'messages': messages,
        }

        return render(request, self.template_name, context)

markaz/templates/teacher/add_study_material.html
{% extends "teacher/base.html" %}
{% block content %}
<title>Add Study Material</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            margin: 0;
            padding: 0;
        }

        form {
            background-color: #fff;
            padding: 20px;
            border-radius: 5px;
            width: 300px;
            margin: 0 auto;
            margin-top: 50px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        }

        h1 {
            text-align: center;
            color: #333;
        }

        label {
            display: block;
            margin-bottom: 10px;
            color: #666;
        }

        input[type="text"],
        input[type="password"],
        input[type="email"] {
            width: 100%;
            padding: 10px;
            border-radius: 5px;
            border: 1px solid #ccc;
            margin-bottom: 20px;
            box-sizing: border-box;
        }

        input[type="submit"] {
            background-color: #333;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        input[type="submit"]:hover {
            background-color: #555;
        }

        p {
            text-align: center;
        }

        /* Add styles for the file preview */
        #file-preview {
            text-align: center;
        }
    </style>
    <h1>Add Study Material</h1>
    <form method='post' enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <div id="file-preview"></div>
        <input type="submit" value="Add Study Material">
    </form>
    <script>
        // Full-screen mode for an element
        function toggleFullScreen(element) {
            if (!document.fullscreenElement) {
                element.requestFullscreen().catch((err) => {
                    console.error(`Error attempting to enable full-screen mode: ${err.message}`);
                });
            } else {
                document.exitFullscreen();
            }
        }
    
        // Function to preview selected file
        function previewFile() {
            const input = document.querySelector('#id_file');
            const preview = document.querySelector('#file-preview');
    
            input.addEventListener('change', function () {
                while (preview.firstChild) {
                    preview.removeChild(preview.firstChild);
                }
    
                if (input.files.length > 0) {
                    const file = input.files[0];
    
                    // Checking that the file is image
                    if (file.type.startsWith('image/')) {
                        const image = document.createElement('img');
                        image.src = URL.createObjectURL(file);
                        image.style.width = '100%';
                        image.style.height = 'auto';
                        preview.appendChild(image);
    
                        // Added event listener for enable full-screen mode
                        image.addEventListener('click', () => {
                            toggleFullScreen(image);
                        });
                    }
                    // Checking that the file is PDF
                    else if (file.type === 'application/pdf') {
                        const iframe = document.createElement('iframe');
                        iframe.src = URL.createObjectURL(file);
                        iframe.style.width = '100%';
                        iframe.style.height = '500px';
                        preview.appendChild(iframe);
                    
                        // Added event listener for enable full-screen mode (it is not working because some browsers didn't support this function)
                        iframe.addEventListener('click', () => {
                            toggleFullScreen(iframe);
                        });
                    }
                    // Checking that the file is video
                    else if (file.type.startsWith('video/')) {
                        const video = document.createElement('video');
                        video.src = URL.createObjectURL(file);
                        video.style.width = '100%';
                        video.style.height = 'auto';
                        video.controls = true; // For video controls like pause and play
                        preview.appendChild(video);
    
                        // Added event listener for enable full-screen mode
                        video.addEventListener('click', () => {
                            toggleFullScreen(video);
                        });
                    }
                    // This will handle other file types
                    else {
                        const errorText = document.createElement('p');
                        errorText.textContent = 'Unsupported file type. Please select an image, PDF, or video file.';
                        preview.appendChild(errorText);
                    }
                }
            });
        }
    
        window.addEventListener('DOMContentLoaded', (event) => {
            previewFile();
        });
    </script>
{% endblock content %}

markaz/templates/teacher/delete_notification.html
<!DOCTYPE html>
<html>
<head>
    <title>Delete Notification</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f5f5f5;
            margin: 0;
            padding: 0;
            text-align: center;
        }

        h2 {
            background-color: #007BFF;
            color: #fff;
            padding: 10px;
        }

        p {
            font-size: 18px;
            margin: 20px 0;
        }

        form {
            margin: 20px 0;
        }

        button[type="submit"] {
            background-color: #ff4646;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            display: block;
            margin: 0 auto;
        }

        button[type="submit"]:hover {
            background-color: #ff0000;
        }

        a {
            text-decoration: none;
            color: #007BFF;
        }

        a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <h2>Delete Notification</h2>
    <p>Are you sure you want to delete this notification?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Delete Notification</button>
    </form>
    <a href="{% url 'list_notification' %}">Cancel and go back</a>
</body>
</html>

markaz/templates/teacher/delete_study_material.html
<!DOCTYPE html>
<html>
<head>
    <title>Delete Study Material</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f5f5f5;
            margin: 0;
            padding: 0;
            text-align: center;
        }

        h2 {
            background-color: #007BFF;
            color: #fff;
            padding: 10px;
        }

        p {
            font-size: 18px;
            margin: 20px 0;
        }

        form {
            margin: 20px 0;
        }

        button[type="submit"] {
            background-color: #ff4646;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            display: block;
            margin: 0 auto;
        }

        button[type="submit"]:hover {
            background-color: #ff0000;
        }

        a {
            text-decoration: none;
            color: #007BFF;
        }

        a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <h2>Delete Study Material</h2>
    <p>Are you sure you want to delete this study material?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Delete Study Material</button>
    </form>
    <a href="{% url 'uploded_materials' %}">Cancel and go back</a>
</body>
</html>

markaz/templates/teacher/list_notifications.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Exam List</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.0/css/all.min.css">

    <style>
        table {
            border-collapse: collapse;
            width: 100%;
            }

            th, td {
            text-align: center;
            padding: 8px;
            }

            tr:nth-child(even){background-color: #f2f2f2}

            th {
            background-color: #04AA6D;
            color: white;
            }
        p{
            text-align: center;
        }
    </style>
</head>
<body>
    <h1>Notification List</h1>
    <table>
        <thead>
            <tr>
                <th>Sender</th>
                <th>Message</th>
                <th>Sended Date</th>
                <th>Scheduled Date</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for notification in notifications %}
            <tr>
                <td>{{ notification.sender }}</td>
                <td>{{ notification.message }}</td>
                <td>{{ notification.timestamp }}</td>
                <td>{{ notification.scheduled_at }}</td>

                <td><a href="{% url 'update_notification' notification.id %}"><i class="fas fa-edit"></i></a></td>
                <td><a href="{% url 'delete_notification' notification.id %}"><i class="fas fa-trash"></i></a></td>
            </tr>
            {% endfor %}
        </tbody>

    </table>
    <br><br>
    <p> <a href="{% url "teacher_home" %}">Back to Home</a></p>

</body>
</html>

markaz/templates/teacher/mark_attendance.html
{% extends "teacher/base.html" %}
{% block content %}
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f2f2f2;
    }

    h1 {
      text-align: center;
      color: #333;
    }

    form {
      background-color: #fff;
      padding: 20px;
      border-radius: 5px;
      width: 300px;
      margin: 0 auto;
      margin-top: 50px;
      box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
    }


    label {
      display: block;
      margin-bottom: 10px;
      color: #666;
    }

    input[type="checkbox"] {
      width: 100%;
      padding: 10px;
      border-radius: 5px;
      border: none;
      margin-bottom: 20px;
      box-sizing: border-box;
      border: 1px solid #ccc;
    }

    input[type="submit"] {
      background-color: #333;
      color: #fff;
      padding: 10px 20px;
      border: none;
      border-radius: 5px;
      cursor: pointer;
    }
    
    input[type="submit"]:hover {
      background-color: #555;
    }
    p{
        text-align : center;

    }
  </style>
  <h1>Mark Attendance</h1>
  <form method="post">
    {% csrf_token %}
    
    <p>Date: {{ attendance.date }}</p>
    <p>Teacher: {{ attendance.teacher.name }}</p>
    
    {% comment %} Morning Attendance {% endcomment %}
    {% if time_allowed_for_morning %}
      <div class="form-group">
        <label for="morning_attendance">Morning Attendance:</label>
        <input type="checkbox" id="morning_attendance" name="morning_attendance" {% if attendance.morning_attendance %}checked{% endif %}>
      </div>
    {% else %}
      <p>Morning attendance can only be submitted before 12 PM.</p>
    {% endif %}
    
    {% comment %} Afternoon Attendance {% endcomment %}
    {% if time_allowed_for_afternoon %}
      <div class="form-group">
        <label for="afternoon_attendance">Afternoon Attendance:</label>
        <input type="checkbox" id="afternoon_attendance" name="afternoon_attendance" {% if attendance.afternoon_attendance %}checked{% endif %}>
      </div>
    {% else %}
      <p>Afternoon attendance can only be submitted after 12 PM.</p>
    {% endif %}
    
    <br>
    
    <input type="submit" value="Submit">
  </form>
  {% if messages %}
    <ul class="messages">
      {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
    </ul>
  {% endif %}
{% endblock content %}

markaz/templates/teacher/no_permission.html
<!DOCTYPE html>
<html>
<head>
    <title>No Permission</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
        }
        .container {
            text-align: center;
            margin-top: 100px;
        }
        h1 {
            color: #FF0000;
        }
        p {
            font-size: 18px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Access Denied</h1>
        <p>Sorry, you do not have permission to access this page.</p>
    </div>
</body>
</html>

markaz/templates/teacher/send_notification.html
{% extends "teacher/base.html" %}
{% block content %}
<style>
  form {
    background-color: #fff;
    padding: 20px;
    border-radius: 5px;
    width: 350px;
    margin: 0 auto;
    margin-top: 50px;
    box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
}

 h1 {
    text-align: center;
    color: #333;
}

form label {
    display: block;
    margin-bottom: 10px;
    color: #666;
}

form input[type="text"] {
    width: 100%;
    padding: 10px;
    border-radius: 5px;
    border: none;
    margin-bottom: 20px;
    box-sizing: border-box;
    border: 1px solid #ccc;
}

form button[type="submit"] {
    background-color: #333;
    color: #fff;
    padding: 10px 20px;
    border: none;
    border-radius: 5px;
    cursor: pointer;
}

form button[type="submit"]:hover {
    background-color: #555;
}
</style>

<h1>Send Notification</h1>
<form method="post">
  {% csrf_token %}
  <label for="recipient">Recipient</label>
  {{ form.recipient }}
  <br><br>
  <input type="text" name="message" placeholder="Message" required>
  <label for="scheduled_at">Scheduled_at</label>
  <input type="datetime-local" name="scheduled_at" required>
  <br><br>
  <button type="submit">Send Notification</button>
</form>
{% endblock content %}

markaz/templates/teacher/teacher_announcements.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="refresh" content="10">
    <title>Teacher Announcements</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            margin: 0;
            padding: 0;
        }

        header {
            background-color: yellow;
            color: black;
            text-align: center;
            padding: 20px 0;
        }

        h1 {
            margin: 0;
        }

        .container {
            max-width: 800px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        .announcement {
            border: 1px solid #ccc;
            padding: 10px;
            margin-bottom: 20px;
        }

        .announcement h2 {
            margin-top: 0;
        }

        .announcement p {
            margin: 10px 0;
        }
    </style>
</head>
<body>
    <header>
        <h1>Announcements</h1>
    </header>
    <div class="container">
        <form method="post" id="myForm">
            {% csrf_token %}
            
            {% for announcement in announcements %}
                <div class="announcement" data-announcement-id="{{ announcement.id }}">
                    <h2>{{ announcement.title }}</h2>
                    <p>{{ announcement.content }}</p>
                    <p>Posted by: {{ announcement.user }}</p>
                    <p>Posted on: {{ announcement.created_at }}</p>
                </div>
            {% endfor %}
        </form>
    </div>

    <script>
        function checkAnnouncementStatus() {
            var currentTime = new Date();
            
            $(".announcement").each(function () {
                var announcement = $(this);
                var announcementTime = new Date(announcement.data("announcement-time"));
                var difference = currentTime - announcementTime;
                
                // Announcement want remove after 1 day automatically
                if (difference >= 24 * 60 * 60 * 1000) {
                    announcement.hide();
                } 
            });
        }
    </script>
    

</body>
</html>